### ISSUE TITLE
Fix for duplicated call in constructor

### ISSUE THREAD

**Issue by simonardejr** [hashemirafsan/php-csv-export#1]
Hello there! 👋

I've noticed that you are calling setHeaders() twice in the constructor method (lines 37 and 38). This overwrites headers with rows. 😀

**Comment by hashemirafsan** [comment]
> Hello there! 👋
> 
> I've noticed that you are calling setHeaders() twice in the constructor method (lines 37 and 38). This overwrites headers with rows. 😀

Thanks for noticing.
